name: AutoTestingSystem - DiamondGotCat

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0,6,12,18 * * *"

jobs:
  testing-with-all-platforms:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: ubuntu-22.04
          - os: windows-2022
          - os: macos-14
          - os: ubuntu-22.04-arm
          - os: windows-11-arm
    runs-on: ${{ matrix.os }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Git user
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Testing
          run: |
            python main.py

        - name: Commit changes
          run: |
            git add .
            git commit -m "Upload Test Result" || echo "No changes to commit"

        - name: Push changes
          run: git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

